### ISSUE TITLE
File parsing should record parse error if remove_data_before_header removes every row in the table

### ISSUE THREAD

**Issue by jbcooley7** [payscale/fables#39]
When parsing a file and removing data before headers, fables sometimes removes every row but the last row of the file, and returns an empty table having headers corresponding to the data in the last row of the file.

[Example File](https://github.com/payscale/fables/files/3799671/fables-feature-request-example.xlsx)

The request is that in situations where this happens, fables records a ParseError rather than returning the empty table.

**Comment by tojo13** [comment]
This makes total sense. Fables shouldn't assume the last row is a header.

Agreed this should be a parse error.

**Comment by tojo13** [comment]
resolved by https://github.com/payscale/fables/pull/40
