### ISSUE TITLE
Add encoding detection to csv parsing

### ISSUE THREAD

**Issue by jbcooley7** [payscale/fables#58]
Currently, the [parse_csv](https://github.com/payscale/fables/blob/cf45c5bca0632b9f62eea802b7ecadbb3c1c87a1/fables/parse.py#L105) function does not specify an encoding to `pd.read_csv` unless one is provided by the client using the `pandas_kwargs` argument. If no encoding is thus provided by the client, pandas will use the system default, which is `utf-8` for unix systems, and `cp1252` for windows systems. This isn't ideal, and has caused parser errors, e.g. this error from fables running on Linux: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 2: invalid continuation byte`.

@thomasjohns left a TODO in the [sniff_delimiter](https://github.com/payscale/fables/blob/cf45c5bca0632b9f62eea802b7ecadbb3c1c87a1/fables/parse.py#L33) around using `chardet` or `cchardet` to auto-detect encoding. I think we should go ahead and make that change, but expand the scope a little further and detect the encoding for passing to `pd.read_csv` as well.

In testing performance of `chardet` and `cchardet`, Andres Sanz found that `cchardet` is much more performant, but seems to have lower confidence in its detections. So I'd suggest we use `cchardet`, and accept any encoding suggestion with a confidence over 50%.

Anticipated work to do:

- add a detect_encoding function to [parse.py](https://github.com/payscale/fables/blob/cf45c5bca0632b9f62eea802b7ecadbb3c1c87a1/fables/parse.py), similar to `sniff_delimiter`, which uses `cchardet` to detect the encoding, returning the encoding if the confidence is over 50%, raising an error otherwise
- updating the signature of `sniff_delimiter` to accept an encoding argument and removing @thomasjohns’ todo comment
- update `parse_csv` to call `detect_encoding` and pass the result to both `sniff_delimiter` and `pd.read_csv`. This should respect the encoding passed in `pandas_kwargs` if present
- integration tests

**Comment by thomasjohns** [comment]
Thanks for the detailed issue @jbcooley7 ! This enhancement sounds great.

One performance tradeoff to consider when implementing this is _always detect encoding_:
```
encoding = ... call to cchardet ...
df = pd.read_csv(..., encoding=encoding, ...)
```
vs _only detect encoding on failure_:
```
try:
    df = pd.read_csv(... not specifying encoding / assume utf-8 ...)
except UnicodeDecodeError:
    encoding = ... call to cchardet ...
    df = pd.read_csv(..., encoding=encoding, ...)
```
The latter has a much worse worst case (two calls to `pd.read_csv`), but _might_ have a better average case (few calls to cchardet if most files are utf-8).

**Comment by jbcooley7** [comment]
@thomasjohns ya that's something Andres and I were discussing. It seemed like with cchardet we might get the performance to check every time, and I wasn't sure if that was the idea for your TODO around delimiter detection and the encoding used to do that. I suppose if encoding caused errors more often (a UnicodeDecodeError was less exceptional) then it might make sense to _always detect_, but since that is less common (at least in our use case) I can see the argument for encoding detection as a fallback and prioritizing the average case.

**Comment by Andres-Endava** [comment]
Hi @thomasjohns. I was evaluating our options here:
1.  The always detect encoding. Calling the new detection function at the beginning of `parse_csv` and then using the encoding type in both `sniff_delimiter` and `parse_csv`.
2.  The detect encoding in failure. Do have you have an idea of how to implement the encoding type in the `sniff_delimiter`? For this case, my only idea is to call the new detection function inside the `sniff_delimiter` and in the `except UnicodeDecodeError` block when the `df = pd.read_csv(...)` fails.

![image](https://user-images.githubusercontent.com/85899020/126713465-a1e45d32-f671-423d-8d94-6315ad60591a.png)

Does this sound good to you?

**Comment by thomasjohns** [comment]
Aw I didn't initially realize that the encoding is important for both `sniff_delimiter` and `pd.read_csv`. That makes things pretty tricky.

I like how you approached option 1 (with adding an encoding argument to `sniff_delimiter`)! I think that one theoretical gotcha is that modifying `pandas_kwargs` will result in the users passed `pandas_kwargs` reference getting modified, which they might not expect. I think it would be better not to modify it.

I had a tough time thinking through the implementation for option 2. I think it is made a little cleaner with a helper function that combines both functions that take in an `encoding` argument into a single helper function with the wrapping `UnicodeDecodeError`. Here is an _untested_ attempt:
```
# update sniff_delimiter to take in an encoding, but defaulting to utf-8 if encoding is None or not passed


def _extract_data_frame_from_csv(
    bytesio: IO[bytes],
    *,
    pandas_kwargs: Dict[str, Any],
) -> pd.DataFrame:
    encoding = pandas_kwargs.get("encoding")
    try:
        delimiter = sniff_delimiter(bytesio, encoding)
    except csv.Error:
        delimiter = ","
    return pd.read_csv(
        bytesio,
        skip_blank_lines=True,
        sep=delimiter,
        encoding=encoding,
        **pandas_kwargs,
    )


def parse_csv(
    bytesio: IO[bytes],
    *,
    force_numeric: bool = True,
    pandas_kwargs: Dict[str, Any],
) -> pd.DataFrame:
    user_supplied_encoding = pandas_kwargs.get("encoding")
    try:
        df = _extract_data_frame_from_csv(bytesio, **pandas_kwargs)
    except UnicodeDecodeError:
        if user_supplied_encoding is not None:
            # I think its better to just error in this case rather than try to "fix"
            # what the user supplied with a different encoding.
            raise
        else:
            detected_encoding = detect_encoding(bytesio)
            df = _extract_data_frame_from_csv(
                bytesio,
                **{"encoding": detected_encoding, **pandas_kwargs},
            )
    df = post_process_dataframe(df, force_numeric)
    return df
```
My vote would be towards option 2, i.e. choosing theoretical performance over a simpler implementation. But I don't have any data saying for sure that option 2 is actually more performant on average and think that either approach would be an improvement to Fables.

**Comment by Andres-Endava** [comment]
The solution is working fine. I only needed to add an additional `if-else` statement in the `sniff_delimiter` to prevent it from failing in case the `encoding` is missing in the `pandas_kwargs`. `None `would make the `sniff_delimiter` fail.
```
def sniff_delimiter(bytesio: IO[bytes], encoding: str) -> str:
    if encoding is not None:
        sample = bytesio.read(1024 * 4).decode(encoding=encoding)
    else:
        sample = bytesio.read(1024 * 4).decode()
    bytesio.seek(0)
    sniffer = csv.Sniffer()
    dialect = sniffer.sniff(sample, delimiters="".join(ACCEPTED_DELIMITERS))
    return dialect.delimiter
```
