### ISSUE TITLE
sniff_delimiter returns wrong delimiter when csv contains a lot of JSON

### ISSUE THREAD

**Issue by jbcooley7** [payscale/fables#61]
I haven't put together an example that reproduces this yet, as the real-world example csv contains JSON cells with around 26000 characters each of privileged information and I haven't made a test file of comparable size yet.

The expected delimiter is `","`, but `sniff_delimiter` returns `":"`. If I pass the entire byte stream to `csv.Sniffer()` it gets the delimiter right, so I guess `1024 * 4` bytes isn't enough to disambiguate the `","` from the `":"` as possible delimiters with all that JSON in the mix. I'm sure we don't want to pass the entire byte stream every time, and increasing the number of bytes we pass seems like an endless game of whack-a-mole as file sizes get larger.

For our use-case, where the delimiter is known beforehand, it might be enough to just have `parse` accept an `expected_delimiter` argument that gets passed down to the `ParseVisitor` and down to `parse_csv`, calling `sniff_delimiter` as needed if `expected_delimiter` isn't specified. This wouldn't solve the problem for users that don't have prior knowledge of the delimiter, though.

**Comment by jbcooley7** [comment]
Reproducing example:
```
import io

import pandas as pd

from fables.parse import sniff_delimiter

json_ = '{"web-app": {"servlet": [{"servlet-name": "cofaxCDS", "servlet-class": "org.cofax.cds.CDSServlet", "init-param": {"configGlossary:installationAt": "Philadelphia, PA", "configGlossary:adminEmail": "ksm@pobox.com", "configGlossary:poweredBy": "Cofax", "configGlossary:poweredByIcon": "/images/cofax.gif", "configGlossary:staticPath": "/content/static", "templateProcessorClass": "org.cofax.WysiwygTemplate", "templateLoaderClass": "org.cofax.FilesTemplateLoader", "templatePath": "templates", "templateOverridePath": "", "defaultListTemplate": "listTemplate.htm", "defaultFileTemplate": "articleTemplate.htm", "useJSP": false, "jspListTemplate": "listTemplate.jsp", "jspFileTemplate": "articleTemplate.jsp", "cachePackageTagsTrack": 200, "cachePackageTagsStore": 200, "cachePackageTagsRefresh": 60, "cacheTemplatesTrack": 100, "cacheTemplatesStore": 50, "cacheTemplatesRefresh": 15, "cachePagesTrack": 200, "cachePagesStore": 100, "cachePagesRefresh": 10, "cachePagesDirtyRead": 10, "searchEngineListTemplate": "forSearchEnginesList.htm", "searchEngineFileTemplate": "forSearchEngines.htm", "searchEngineRobotsDb": "WEB-INF/robots.db", "useDataStore": true, "dataStoreClass": "org.cofax.SqlDataStore", "redirectionClass": "org.cofax.SqlRedirection", "dataStoreName": "cofax", "dataStoreDriver": "com.microsoft.jdbc.sqlserver.SQLServerDriver", "dataStoreUrl": "jdbc:microsoft:sqlserver://LOCALHOST:1433;DatabaseName=goon", "dataStoreUser": "sa", "dataStorePassword": "dataStoreTestQuery", "dataStoreTestQuery": "SET NOCOUNT ON;select test=\'test\';", "dataStoreLogFile": "/usr/local/tomcat/logs/datastore.log", "dataStoreInitConns": 10, "dataStoreMaxConns": 100, "dataStoreConnUsageLimit": 100, "dataStoreLogLevel": "debug", "maxUrlLength": 500}}, {"servlet-name": "cofaxEmail", "servlet-class": "org.cofax.cds.EmailServlet", "init-param": {"mailHost": "mail1", "mailHostOverride": "mail2"}}, {"servlet-name": "cofaxAdmin", "servlet-class": "org.cofax.cds.AdminServlet"}, {"servlet-name": "fileServlet", "servlet-class": "org.cofax.cds.FileServlet"}, {"servlet-name": "cofaxTools", "servlet-class": "org.cofax.cms.CofaxToolsServlet", "init-param": {"templatePath": "toolstemplates/", "log": 1, "logLocation": "/usr/local/tomcat/logs/CofaxTools.log", "logMaxSize": "", "dataLog": 1, "dataLogLocation": "/usr/local/tomcat/logs/dataLog.log", "dataLogMaxSize": "", "removePageCache": "/content/admin/remove?cache=pages&id=", "removeTemplateCache": "/content/admin/remove?cache=templates&id=", "fileTransferFolder": "/usr/local/tomcat/webapps/content/fileTransferFolder", "lookInContext": 1, "adminGroupID": 4, "betaServer": true}}], "servlet-mapping": {"cofaxCDS": "/", "cofaxEmail": "/cofaxutil/aemail/*", "cofaxAdmin": "/admin/*", "fileServlet": "/static/*", "cofaxTools": "/tools/*"}, "taglib": {"taglib-uri": "cofax.tld", "taglib-location": "/WEB-INF/tlds/cofax.tld"}}}'

df = pd.DataFrame(dict(a=['one'], b=['two'], c=[json_]))
stream = io.BytesIO(df.to_csv(index=False).encode('utf-8'))
sniff_delimiter(stream)  # returns ":"
```

**Comment by thomasjohns** [comment]
Thanks for the detailed report! This is a fascinating edge case!

`expected_delimiter` feels like a good, practical way to solve this. Agreed, that it cuts through the Fables abstraction layer a bit with the user having to have an expectation for the file.

I wonder if it would be possible, as an alternative to reading in `1024 * 4` bytes, to have `sniff_delimiter` calculate the number of bytes in e.g. the first 5 or so non-blank lines (or perhaps lines containing at least one `,`) (maybe doing something with seen `\n`'s), and then use that many bytes. Maybe `1024 * 4` isn't "wide" enough to pull in complete lines in this case, and that's why the underlying `csv.Sniffer` chooses the wrong delimiter?

Another hack could be to have a line restricting `fables.parse.ACCEPTED_DELIMITERS = {",", "\t"}` (not sure if this actually work). This could be made into less of a hack if we allowed the user to explicitly set options something like the way pandas has `pd.options...`. This would be useful too for other Fables variables that could be seen as options including `FRACTION_OF_BLANK_HEADERS_ALLOWED`, `MAX_FILE_SIZE`, and `OS_PATTERNS_TO_SKIP`.

**Comment by jbcooley7** [comment]
Both those approaches make sense to me. I tried a quick test of the first approach, but found that it still returned the wrong delimiter. Sample code below.
```
import csv

from fables.parse import ACCEPTED_DELIMITERS

# skipping first few lines of example in earlier comment
df = pd.DataFrame(dict(a=list('abc'), b=list('123'), c=[json_]*3))
stream = io.BytesIO(df.to_csv(index=False).encode('utf-8'))
i = 0
sample = b""
for row in stream:
    if i >= 3:
        break
    sample += row
    i += 1
stream.seek(0)
sniffer = csv.Sniffer()
dialect = sniffer.sniff(sample.decode(encoding="utf-8"), delimiters="".join(ACCEPTED_DELIMITERS))
dialect.delimiter  # returns ":"
```

This is feeling more like a limitation of `csv.Sniffer` in general.

I did try the other approach, of monkey patching the ACCEPTED_DELIMITERS, but that didn't work. I really like the idea of making the options configurable like [pandas](https://github.com/pandas-dev/pandas/blob/master/pandas/core/config_init.py), though I'm not sure I have the bandwidth to implement that robustly. Looking at the pandas implementation, they abstracted validation and callbacks really nicely, ideally we'd have a similar scheme for validating the values and providing feedback if the user uses an invalid value.

**Comment by thomasjohns** [comment]
Thanks for giving these approaches a try!

I stumbled across this library: https://github.com/alan-turing-institute/CleverCSV and just tried `pip install clevercsv` and replacing `csv` with `clevercsv` with your code listing and it returned `,`!

I forgot about this, but I think we actually considered using clevercsv near the beginning of Fables development, but the built-in `csv.Sniffer` was working well enough at the time ...

I'd be curious to see if it works with your real world example.

**Comment by jbcooley7** [comment]
Just gave that a try, it did work on my real-world example! This seems like the best path forward. No interface changes, nothing new to implement. I'll work on a PR making that update. Thanks for the suggestion!!
